sudo: false
dist: trusty
services:
  - docker
before_install:
  - docker pull ubuntu
  - docker run -d -i -t --name rust-builder -v $(pwd):/home/ubuntu/redfish -w /home/ubuntu/redfish ubuntu:16.04 /bin/bash
  - docker exec rust-builder /usr/bin/apt-get update
  - docker exec rust-builder apt-get -y install curl pkg-config make clang
  - docker exec rust-builder curl https://sh.rustup.rs -o rustup.sh
  - docker exec rust-builder chmod +x rustup.sh
  - docker exec rust-builder ./rustup.sh -y
script:
  - docker exec rust-builder /root/.cargo/bin/cargo build --verbose --all
