[package]
name = "redfish"
version = "0.1.0"
authors = ["Chris Holcombe <xfactor973@gmail.com>"]
edition = "2018"

[build-dependencies]
reqwest = "~0.9"
serde_json = "~1.0"

[dependencies]
log = "~0.4"
reqwest = "~0.9"
serde_derive = "~1.0"
serde = "~1.0"
serde_json = "~1.0"